baseURL = "https://tigerbleu2015.github.io/Nexus/"
languageCode = "en-us"
title = "TechPulse"
theme = "techpulse"
paginate = 9

[params]
  description = "The latest in Gaming, AR, VR & Technology"
  tagline = "Next-Gen Tech. Zero Delay."
  author = "TechPulse Editorial"

[taxonomies]
  category = "categories"
  tag = "tags"
